spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      idle-timeout: 12000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    open-in-view: false
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    enabled: true
    enable-spring-el-compiler: false
    encoding: UTF-8
    mode: HTML
    prefix: file:./templates/
    suffix: .html
    reactive:
      max-chunk-size: 0
    servlet:
      content-type: text/html