-- MySQL Script generated by MySQL Workbench
-- Wed May 23 18:20:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tutorial_spring_web
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tutorial_spring_web` ;

-- -----------------------------------------------------
-- Schema tutorial_spring_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tutorial_spring_web` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
SHOW WARNINGS;
USE `tutorial_spring_web` ;

-- -----------------------------------------------------
-- Table `tutorial_spring_web`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial_spring_web`.`user_account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
